### ISSUE TITLE
Final Testing

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#114]
- [x] Admin Account Management Service
  - [x] Create
  - [x] Read
  - [x] Update
- [x] Examiner Exam Management
  - [x] Create
  - [x] Read
  - [x] Update
  - [x] Delete
- [x] Examiner Statistical Tools
  - [x] The charts work
- [ ] Examinee Take Exam
  - [x] Can see exam detail
  - [x] Can see time left
  - [x] OK exam layout
  - [x] Exam Submission
  - [ ] Can see score (?)
  - [x] Can continue exam if disconnected
  - [x] Can search exam
- [x] Examinee Exam Navigation
  - [x] Dashboard
  - [x] Each exam's information
- [x] Login and Authentication

**Comment by leehoang2000** [comment]
Problems:
 - Click on save change delete unsaved questions (and potentially de-sync question id ?)
 - Question Page get dupplicate keys
    dump: api_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
api_1      |     raise translated_error from error
api_1      | sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "question_pkey"
api_1      | DETAIL:  Key (question_id)=(24) already exists.
api_1      | [SQL: INSERT INTO question (question_content, exam_id, question_group_id, question_type_id) VALUES (%s, %s, %s, %s) RETURNING question.question_id]
api_1      | [parameters: ('eh', 8, 1, 1)]
api_1      | (Background on this error at: http://sqlalche.me/e/14/gkpj)

**Comment by leehoang2000** [comment]
docker log of exam deletion:
api_1      | Traceback (most recent call last):
api_1      |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
api_1      |     result = await app(self.scope, self.receive, self.send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
api_1      |     return await self.app(scope, receive, send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
api_1      |     await super().__call__(scope, receive, send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
api_1      |     await self.middleware_stack(scope, receive, send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
api_1      |     raise exc from None
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
api_1      |     await self.app(scope, receive, _send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in __call__
api_1      |     await self.simple_response(scope, receive, send, request_headers=headers)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response
api_1      |     await self.app(scope, receive, send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
api_1      |     raise exc from None
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
api_1      |     await self.app(scope, receive, sender)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
api_1      |     await route.handle(scope, receive, send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
api_1      |     await self.app(scope, receive, send)
api_1      |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
api_1      |     response = await func(request)
api_1      |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
api_1      |     dependant=dependant, values=values, is_coroutine=is_coroutine
api_1      |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
api_1      |     return await dependant.call(**values)
api_1      |   File "./app/api/exam/router.py", line 255, in update_question
api_1      |     is_viewer = await qs.check_exam_viewer(exam_id, account)
api_1      |   File "./app/services/exam_service.py", line 237, in check_exam_viewer
api_1      |     if(exam_id > 0):
api_1      | TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by alitonia** [comment]
> docker log of exam deletion: api_1 | Traceback (most recent call last): api_1 | File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi api_1 | result = await app(self.scope, self.receive, self.send) api_1 | File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in **call** api_1 | return await self.app(scope, receive, send) api_1 | File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 208, in **call** api_1 | await super().**call**(scope, receive, send) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in **call** api_1 | await self.middleware_stack(scope, receive, send) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in **call** api_1 | raise exc from None api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in **call** api_1 | await self.app(scope, receive, _send) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 86, in **call** api_1 | await self.simple_response(scope, receive, send, request_headers=headers) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 142, in simple_response api_1 | await self.app(scope, receive, send) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in **call** api_1 | raise exc from None api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in **call** api_1 | await self.app(scope, receive, sender) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in **call** api_1 | await route.handle(scope, receive, send) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle api_1 | await self.app(scope, receive, send) api_1 | File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 52, in app api_1 | response = await func(request) api_1 | File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app api_1 | dependant=dependant, values=values, is_coroutine=is_coroutine api_1 | File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 159, in run_endpoint_function api_1 | return await dependant.call(**values) api_1 | File "./app/api/exam/router.py", line 255, in update_question api_1 | is_viewer = await qs.check_exam_viewer(exam_id, account) api_1 | File "./app/services/exam_service.py", line 237, in check_exam_viewer api_1 | if(exam_id > 0): api_1 | TypeError: '>' not supported between instances of 'str' and 'int'

Done

> Problems:
> 
>     * Click on save change delete unsaved questions (and potentially de-sync question id ?)
> 
>     * Question Page get dupplicate keys
>       backend dump:
>       api_1      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 652, in _handle_exception
>       api_1      |     raise translated_error from error
>       api_1      | sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "question_pkey"
>       api_1      | DETAIL:  Key (question_id)=(24) already exists.
>       api_1      | [SQL: INSERT INTO question (question_content, exam_id, question_group_id, question_type_id) VALUES (%s, %s, %s, %s) RETURNING question.question_id]
>       api_1      | [parameters: ('eh', 8, 1, 1)]
>       api_1      | (Background on this error at: http://sqlalche.me/e/14/gkpj)
> 
>     * Can't delete exam
> 
>     * Can't search exam

Also done except delete unsaved

**Comment by alitonia** [comment]
Acceptable level of completion
