### ISSUE TITLE
assets folder init to store img, icon, font, each divided into subfolders.

### ISSUE THREAD

**Issue by DrakeGoCoding** [alitonia/multi-choice-system#58]
init font.css to 
- define font with font-face, 
- define font for heading, title, subtitle, label, field input, text content, hint 
- reference: 
![image](https://user-images.githubusercontent.com/57493556/140483508-f1a2f174-130c-4dc9-9e5d-bcddad4433b7.png)

**Comment by tapicationer** [comment]
Folders: src/assets/fonts, src/assets/img
Files: src/font.css (font face, fonts)
