### ISSUE TITLE
Examiner Statistical tools

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#74]
Finished delivery must satisfy:

- [ ] Examiner can see exam score distribution graph
- [ ] Examiner can see max, min score

**Comment by tapicationer** [comment]
Will confirm, but request meeting of members herein, if possible

**Comment by alitonia** [comment]
This task will require some api design and db change. I am available for meeting from 9pm to 11pm GMT+7 on Dec 18 or 19. I will handle the backend of this task.
Currently useFakeQuery does not have this mock yet. I will update this tommorrow.

**Comment by alitonia** [comment]
Hmm this issue api will have to wait for https://github.com/alitonia/multi-choice-system/issues/77. If anyone is deving the frontend, do try to useFakeQuery it in the mean time

**Comment by alitonia** [comment]
API is currently at https://github.com/alitonia/multi-choice-system/pull/98 🤗

**Comment by alitonia** [comment]
Done
