### ISSUE TITLE
Examiner monitor on-going test

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#75]
Finished delivery must satisfy:

- [ ] Examiner can see participants, their progress, 
- [ ] (OPTIONAL) Examiner can suspend a participant if they detect any cheating

**Comment by tapicationer** [comment]
Will confirm, but request meeting of members herein, if possible

**Comment by alitonia** [comment]
I am available on Dec 18 and 19, between 20 and 23 GMT+0. We can have a small meeting on existing discord channel.
I will handle the backend
