### ISSUE TITLE
Examiner exam management

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#76]
Finished delivery must satisfy:

- [ ] Examiner can CRUD exams
- [ ] Exams created must appear in the examinee's dashboard
- [ ] Examiner can register exams for examinee

FE must create Dashboard (Examiner) Page,

**Comment by narutox900** [comment]
confirmed

**Comment by alitonia** [comment]
API is currently here https://github.com/alitonia/multi-choice-system/pull/96. Frontend dev can merge this first without waiting for main marge. 🤠

**Comment by alitonia** [comment]
Done
