### ISSUE TITLE
Examinee exam navigation

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#78]
Finished delivery must satisfy:
- [x] Examinee can choose to view each exam's information(name, subject, creator, start time, duration)
- [ ] Examinee can browse registered exams in their dashboard

Dashboard (Examinee) and Exam Page is available

**Comment by alitonia** [comment]
This part is almost done, need api and wiring. API will be done after Dec 18. @DrakeGoCoding can start wiring the data with the new useFakeQuery 😚

**Comment by linh442k** [comment]
I will be in charge of Exam Page because I accidentally coded it already :v

**Comment by alitonia** [comment]
Done
