### ISSUE TITLE
Admin Management Service

### ISSUE THREAD

**Issue by leehoang2000** [alitonia/multi-choice-system#80]
Finished delivery must satisfy:

- [x] Admin can CRUD the accounts
- [x] Users can edit their account on account page, but they can't change their role
FE must create Dashboard (Admin), Create Account and Edit Account Page

**Comment by alitonia** [comment]
I will handle the backend side of this. Expected API to be ready on Dec 18

**Comment by linh442k** [comment]
khi nào có api thì ông comment vào đây 1 cái response mẫu mà api trả về xem @alitonia 
dashboard thì trả về list account,
add, delete account thì ko cần trả về
edit account thì cần trả về thông tin ban đầu của account gốc

**Comment by alitonia** [comment]
Tôi định làm như api draft ý, ông thấy có chỗ nào cần sửa thì comment lại nha

**Comment by alitonia** [comment]
API đang ở nhánh dev/alitonia/#80, đang chờ review. Nếu ông đang cần rồi thì merge luôn nhánh ý cho tiện, không thì dùng fakeQuery tôi cũng update data form rồi

**Comment by linh442k** [comment]
oke, giờ toi cũng chưa làm màn đấy, nên là ô cứ vứt luôn data mockup vào phần comment này toi xem qua luôn

**Comment by alitonia** [comment]
Data ông cứ check mock nhá, tôi lười quá

**Comment by linh442k** [comment]
admin thì create, edit, delete thoải mái
examinee và examiner thì chỉ có thể edit trừ trường role đúng ko?
@alitonia @leehoang2000

**Comment by alitonia** [comment]
Đúng rồi đoa. Tôi đang nghĩ là có khi không cho edit cả email nữa cho dễ. Nếu ông cắm API thì hiện chưa có phân role đâu, vì chưa có jwt😑

**Comment by alitonia** [comment]
Done
